import { ErrorCode } from '../common/errors';


export const ERROR_CODE_HTTP_STATUS: Readonly<Record<ErrorCode, number>> = {
  [ErrorCode.VALIDATION_FAILED]: 400,
  [ErrorCode.INVALID_AMOUNT]: 400,
  [ErrorCode.UNSUPPORTED_CURRENCY]: 400,
  [ErrorCode.SAME_CURRENCY]: 400,
  [ErrorCode.UNSUPPORTED_CURRENCY_PAIR]: 400,
  [ErrorCode.IDEMPOTENCY_KEY_REQUIRED]: 400,
  [ErrorCode.IDEMPOTENCY_KEY_INVALID]: 400,
  [ErrorCode.INVALID_CURSOR]: 400,
  [ErrorCode.VERIFICATION_FAILED]: 400,
  [ErrorCode.WITHDRAWAL_CODE_INVALID]: 400,

  [ErrorCode.UNAUTHENTICATED]: 401,
  [ErrorCode.INVALID_CREDENTIALS]: 401,

  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.ACCOUNT_SUSPENDED]: 403,
  [ErrorCode.EMAIL_NOT_VERIFIED]: 403,
  [ErrorCode.SELF_APPROVAL_FORBIDDEN]: 403,
  [ErrorCode.BREAK_GLASS_NOT_ALLOWED]: 403,

  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.ACCOUNT_NOT_FOUND]: 404,
  [ErrorCode.RESERVATION_NOT_FOUND]: 404,
  [ErrorCode.FUNDING_NOT_FOUND]: 404,
  [ErrorCode.WITHDRAWAL_NOT_FOUND]: 404,
  [ErrorCode.WITHDRAWAL_BENEFICIARY_NOT_FOUND]: 404,
  [ErrorCode.BENEFICIARY_NOT_READY]: 409,
  [ErrorCode.WITHDRAWALS_DISABLED]: 503,
  [ErrorCode.QUOTE_NOT_FOUND]: 404,
  [ErrorCode.TRANSACTION_NOT_FOUND]: 404,
  [ErrorCode.RECONCILIATION_BREAK_NOT_FOUND]: 404,
  [ErrorCode.APPROVAL_NOT_FOUND]: 404,
  [ErrorCode.USER_NOT_FOUND]: 404,
  [ErrorCode.RECONCILIATION_RUN_NOT_FOUND]: 404,

  [ErrorCode.INSUFFICIENT_FUNDS]: 409,
  [ErrorCode.FUNDS_RESERVED]: 409,
  [ErrorCode.QUOTE_EXPIRED]: 409,
  [ErrorCode.QUOTE_ALREADY_USED]: 409,
  [ErrorCode.IDEMPOTENCY_KEY_REUSE]: 409,
  [ErrorCode.REQUEST_IN_PROGRESS]: 409,
  [ErrorCode.PERIOD_LOCKED]: 409,
  [ErrorCode.ALREADY_CORRECTED]: 409,
  [ErrorCode.RESERVATION_NOT_ACTIVE]: 409,
  [ErrorCode.RESERVATION_CONFLICT]: 409,
  [ErrorCode.PRICE_LIMIT_EXCEEDED]: 409,
  [ErrorCode.RECONCILIATION_RUN_LEASE_LOST]: 409,
  [ErrorCode.APPROVAL_ALREADY_DECIDED]: 409,
  [ErrorCode.APPROVAL_EXPIRED]: 409,
  [ErrorCode.APPROVAL_REQUESTER_INELIGIBLE]: 409,
  [ErrorCode.BREAK_GLASS_ALREADY_REVIEWED]: 409,
  [ErrorCode.ACTION_PRECONDITION_FAILED]: 409,

  [ErrorCode.PAYLOAD_TOO_LARGE]: 413,
  [ErrorCode.AMOUNT_TOO_SMALL]: 422,
  [ErrorCode.AMOUNT_TOO_LARGE]: 422,
  [ErrorCode.DAILY_LIMIT_EXCEEDED]: 422,
  [ErrorCode.RATE_LIMITED]: 429,

  [ErrorCode.RESOURCE_BUSY]: 503,
  [ErrorCode.FX_RATE_STALE]: 503,
  [ErrorCode.FX_RATE_UNAVAILABLE]: 503,
  [ErrorCode.DEPENDENCY_UNAVAILABLE]: 503,

  [ErrorCode.INVARIANT_VIOLATION]: 500,
  [ErrorCode.LEDGER_UNBALANCED]: 500,
  [ErrorCode.INVALID_POSTING]: 500,
  [ErrorCode.ACCOUNT_CURRENCY_MISMATCH]: 500,
  [ErrorCode.REVERSAL_MISMATCH]: 500,
  [ErrorCode.INVALID_RESERVATION]: 500,
  [ErrorCode.INTERNAL_ERROR]: 500,
  [ErrorCode.HTTP_ERROR]: 400,
};

export const ERROR_CODE_DESCRIPTIONS: Readonly<Record<ErrorCode, string>> = {
  [ErrorCode.VALIDATION_FAILED]: 'The request is malformed. A body/query DTO failure lists `details.violations`; fix the request.',
  [ErrorCode.INVALID_AMOUNT]: 'The amount is not a positive whole number of minor units in range.',
  [ErrorCode.UNSUPPORTED_CURRENCY]: 'The currency is not supported for this operation.',
  [ErrorCode.SAME_CURRENCY]: '`from` and `to` are the same currency.',
  [ErrorCode.UNSUPPORTED_CURRENCY_PAIR]: 'The directional pair is not offered (or not active).',
  [ErrorCode.IDEMPOTENCY_KEY_REQUIRED]: 'This route needs an `Idempotency-Key` header.',
  [ErrorCode.IDEMPOTENCY_KEY_INVALID]: '`Idempotency-Key` must be 16–128 characters of `[A-Za-z0-9_-]`.',
  [ErrorCode.INVALID_CURSOR]: 'The cursor is malformed, from another version, or from a different sort/filter set. Restart from the first page.',
  [ErrorCode.VERIFICATION_FAILED]: 'The email, password and one-time password do not verify an account awaiting verification.',
  [ErrorCode.WITHDRAWAL_CODE_INVALID]: 'The withdrawal code is wrong, expired, already used or replaced by a newer one. Request a new code; retry with a NEW Idempotency-Key (this refusal is stored for the key).',
  [ErrorCode.UNAUTHENTICATED]: 'No valid credentials: missing/expired/revoked access token, a refused refresh token, or a bad webhook signature.',
  [ErrorCode.INVALID_CREDENTIALS]: 'Login refused. Deliberately the same for an unknown email, a wrong password, an unverified or a suspended account.',
  [ErrorCode.FORBIDDEN]: 'Authenticated, but your role may not do this.',
  [ErrorCode.ACCOUNT_SUSPENDED]: 'The account is suspended.',
  [ErrorCode.EMAIL_NOT_VERIFIED]: 'Verify the email address first.',
  [ErrorCode.SELF_APPROVAL_FORBIDDEN]: 'Four-eyes: you may not decide (or review) your own request.',
  [ErrorCode.BREAK_GLASS_NOT_ALLOWED]: 'Break-glass is only for SUSPEND_USER and RATE_OVERRIDE (MANUAL_RATE).',
  [ErrorCode.NOT_FOUND]: 'No such route or resource.',
  [ErrorCode.ACCOUNT_NOT_FOUND]: 'No such ledger account.',
  [ErrorCode.RESERVATION_NOT_FOUND]: 'No such reservation.',
  [ErrorCode.FUNDING_NOT_FOUND]: 'No such funding for this user (unknown and another user\'s are the same answer).',
  [ErrorCode.WITHDRAWAL_NOT_FOUND]: 'No such withdrawal for this user (unknown and another user\'s are the same answer).',
  [ErrorCode.WITHDRAWAL_BENEFICIARY_NOT_FOUND]: 'No such beneficiary for this user (unknown and another user\'s are the same answer).',
  [ErrorCode.BENEFICIARY_NOT_READY]: 'The beneficiary is still being verified with Paystack, or failed: only a READY one can receive a withdrawal.',
  [ErrorCode.WITHDRAWALS_DISABLED]: 'New withdrawals are switched off (or no worker can process them). Earlier requests keep their answers. Transient.',
  [ErrorCode.QUOTE_NOT_FOUND]: 'No such quote for this user (unknown and another user\'s are the same answer).',
  [ErrorCode.TRANSACTION_NOT_FOUND]: 'No such transaction for this user (unknown and another user\'s are the same answer).',
  [ErrorCode.RECONCILIATION_BREAK_NOT_FOUND]: 'No such reconciliation break.',
  [ErrorCode.APPROVAL_NOT_FOUND]: 'No such approval.',
  [ErrorCode.USER_NOT_FOUND]: 'No such user.',
  [ErrorCode.RECONCILIATION_RUN_NOT_FOUND]: 'No such reconciliation run.',
  [ErrorCode.INSUFFICIENT_FUNDS]: 'The available balance does not cover it, even counting held funds: top up.',
  [ErrorCode.FUNDS_RESERVED]: 'The total balance would cover it but part is held by a pending operation: wait for it.',
  [ErrorCode.QUOTE_EXPIRED]: 'The quote\'s 30 seconds are over. Request a new quote.',
  [ErrorCode.QUOTE_ALREADY_USED]: 'Quotes are single-use and this one was executed.',
  [ErrorCode.IDEMPOTENCY_KEY_REUSE]: 'This key was used with a different request body on this route. Use a new key.',
  [ErrorCode.REQUEST_IN_PROGRESS]: 'The same key is being processed right now. Retry after `Retry-After` with the same key.',
  [ErrorCode.PERIOD_LOCKED]: 'The value time falls in a closed reporting period.',
  [ErrorCode.ALREADY_CORRECTED]: 'The original transaction was already corrected.',
  [ErrorCode.RESERVATION_NOT_ACTIVE]: 'The reservation is no longer active.',
  [ErrorCode.RESERVATION_CONFLICT]: 'The reservation exists with different terms.',
  [ErrorCode.PRICE_LIMIT_EXCEEDED]: 'The priced amounts breach `minimumTargetAmount` / `maximumSourceAmount`; `details` has the priced amounts.',
  [ErrorCode.RECONCILIATION_RUN_LEASE_LOST]: 'Internal: a reconciliation run lost its lease.',
  [ErrorCode.APPROVAL_ALREADY_DECIDED]: 'The approval is no longer PENDING (or is a break-glass use, which is never decided).',
  [ErrorCode.APPROVAL_EXPIRED]: 'The approval passed its time to live without a decision.',
  [ErrorCode.APPROVAL_REQUESTER_INELIGIBLE]: 'The requester no longer holds the role (or is no longer active).',
  [ErrorCode.BREAK_GLASS_ALREADY_REVIEWED]: 'This break-glass use was already reviewed (or is not a break-glass use).',
  [ErrorCode.ACTION_PRECONDITION_FAILED]: 'The world does not allow this action now (see `details`).',
  [ErrorCode.PAYLOAD_TOO_LARGE]: 'The body exceeds 100 KB.',
  [ErrorCode.AMOUNT_TOO_SMALL]: 'Below the minimum for this currency or pair.',
  [ErrorCode.AMOUNT_TOO_LARGE]: 'Above the per-operation maximum.',
  [ErrorCode.DAILY_LIMIT_EXCEEDED]: 'The rolling 24-hour limit for this source currency would be exceeded.',
  [ErrorCode.RATE_LIMITED]: 'Too many requests. Retry after `Retry-After` seconds.',
  [ErrorCode.RESOURCE_BUSY]: 'Transient lock or statement timeout. Retry with the SAME `Idempotency-Key`.',
  [ErrorCode.FX_RATE_STALE]: 'No executable rate right now (rates may still be displayed). Transient: retry later with the same key.',
  [ErrorCode.FX_RATE_UNAVAILABLE]: 'No rate can be served at all. Transient.',
  [ErrorCode.DEPENDENCY_UNAVAILABLE]: 'A dependency we cannot work without is down; we fail closed. Transient.',
  [ErrorCode.INVARIANT_VIOLATION]: 'Our bug, failed loudly. Quote the `correlationId`.',
  [ErrorCode.LEDGER_UNBALANCED]: 'Our bug: a posting did not balance. Quote the `correlationId`.',
  [ErrorCode.INVALID_POSTING]: 'Our bug: an invalid posting was refused. Quote the `correlationId`.',
  [ErrorCode.ACCOUNT_CURRENCY_MISMATCH]: 'Our bug: an entry\'s currency differs from its account\'s. Quote the `correlationId`.',
  [ErrorCode.REVERSAL_MISMATCH]: 'Our bug: a reversal did not mirror its original. Quote the `correlationId`.',
  [ErrorCode.INVALID_RESERVATION]: 'Our bug: an invalid reservation settlement. Quote the `correlationId`.',
  [ErrorCode.INTERNAL_ERROR]: 'Unexpected error. Quote the `correlationId`.',
  [ErrorCode.HTTP_ERROR]: 'An HTTP-level refusal without a dedicated code.',
};

export const TRANSIENT_ERROR_CODES: readonly ErrorCode[] = [
  ErrorCode.REQUEST_IN_PROGRESS,
  ErrorCode.RATE_LIMITED,
  ErrorCode.RESOURCE_BUSY,
  ErrorCode.FX_RATE_STALE,
  ErrorCode.FX_RATE_UNAVAILABLE,
  ErrorCode.DEPENDENCY_UNAVAILABLE,
];
